version = 0.1

# Default configuration (can be used for development or sandbox environments)
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "STACK-NAME-DEV"
s3_bucket = "STACK-NAME-DEV-samclisourcebucket"
s3_prefix = "STACK-NAME-DEV-DATA"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

# Production configuration
resolve_s3 = true
parameter_overrides = "VpcCidrBlock=\"10.0.0.0/16\" PublicSubnetCidrBlock=\"10.0.1.0/24\" PrivateSubnetCidrBlock=\"10.0.2.0/24\" LogLevel=\"INFO\" Environment=\"dev\" ProjectName=\"PROJECT-NAME\""
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "STACK-NAME-PROD"
s3_bucket = "STACK-NAME-PROD-samclisourcebucket"  # Update with your S3 bucket name
s3_prefix = "STACK-NAME-PROD-DATA"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
